version: "3"


services:

  my-smart-home-mqtt:
    image: ianstorm/my-smart-home-mqtt:latest
    networks:
      zigbee-net:
        aliases:
          - mqtt-broker
    ports:
      - 1883:1883

  my-smart-home-zigbee2mqtt:
    build: .
    depends_on:
      - my-smart-home-mqtt
    devices:
      - /dev/ttyUSB0
    networks:
      - zigbee-net
    ports:
      - 8099:8099
    volumes:
      - ./app/data/:/app/data/


networks:
  zigbee-net:
